# BMAD™ Core Configuration

prompt:
  - "Welcome and thank you for choosing BMAD™! This is the Core Configuration."
  - "This will impact all selected modules, either additions or upgrades."

bmad_folder:
  prompt: "What is the root that all modules should be installed to?"
  default: ".bmad"
  result: "{value}"

user_name:
  prompt: "What is your name?"
  default: "BMad"
  result: "{value}"

communication_language:
  prompt: "Preferred Chat Language?"
  default: "English"
  result: "{value}"

document_output_language:
  prompt: "Preferred Document Output Language?"
  default: "English"
  result: "{value}"

output_folder:
  prompt: "Where should the generated output default save location be?"
  default: "docs"
  result: "{project-root}/{value}"
