# BMAD™ Creative Intelligence Suite Configuration

code: cis
name: "CIS: Creative Innovation Suite"
default_selected: false # This module will not be selected by default for new installations

prompt:
  - "Thank you for choosing the BMAD™ Creative Intelligence Suite, an early release with much more planned!"
# Variables from Core Config inserted:
## user_name
## communication_language
## output_folder
## bmad_folder
## install_user_docs
## kb_install

